octalmage/robotjs

- binding.gyp
Thanks the start you provided in #17 - I did some investigation on my machine and got the simple mouse example working with some tweaks (I went a little overboard - sorry) to the binding.gyp file.  Hopefully it all still works on MacOS :)
> Compilation for Linux

- src/screengrab.c
> getPixelColor bug fix.

- README.md
Added whitespace to Readme to increase legibility
> Added whitespace

- src/robotjs.cc
Add function keys to CheckKeyCodes
> Add function keys to CheckKeyCodes

- src/mouse.c
- src/mouse.h
- src/robotjs.cc
Mac requires special code to automate a double click, so we need a double click function. Set the second argument of mouseClick to true to perform a double click. 
robot.mouseClick("left", true);
Closes #24.
> Add double click functionality to mouseClick.

- src/robotjs.cc
The mouseToggle function has some simple syntax errors and doesn't work. Here's a fix produced with minimal knowledge on C/C++ .
> Fix mouseToggle

- README.md
...because it was wrong. :star2:
> Fixed the API link

- .travis.yml
Instead of having 4.0.0 hardcoded.
> Test the latest 4.x.x Node.js version.

- README.md
- appveyor.yml
- src/mouse.c
- test/mouse.js
This improves the accuracy of moveMouse #77, and implements automated testing for Windows #105.
Special thanks to @Lexikos(AutoHotkey), @maxdeepfield, and @deltatiger. 
Closes #77.
Closes #105.
> Improve moveMouse accuracy and set up AppVeyor.

- binding.gyp
> Dynamic nan include.

- src/keypress.h
- src/mouse.h
This PR improves OS X El Capitan support for newer versions of Node.js. 
Resolves #118.
> Better El Capitan support.

- README.md
I added an FAQ section to answer frequently asked questions. 
Resolves #123.
> Add FAQ section.

- src/mouse.c
This is the fix described in #39.
> Passing constant instead of zero for mouseButton on mouse move

- src/keycode.h
Would previously hit F19
Resolves #141.
> Fixed F9 key

- src/keycode.h
- src/robotjs.cc
Restructured code a bit to make adding keyboard keycodes much easier.
Added multimedia keys + brightness control. This should be also possible on Cocoa but I didn't have a chance to investigate.
Fixes #91
> Added special multimedia keycodes + restructured code

- src/robotjs.cc
- test/all.js
- test/keyboard.js
- test/mouse.js
- test/screen.js
Like the title says, better tests. They aren't 100% done, but it's much better than what we have now.
> Better tests.

- src/mouse.c
> Workaround for games not detecting mouse moves.

- src/keycode.h
- src/robotjs.cc
Built and tested it under windows10. Cant test it on Mac/Linux
> Adding insert key. Fixes #184

- package.json
> Use prebuild.

- .travis.yml
Setup Travis CI to also build/test on Mac. 
Resolves #198.
> Mac continuous integration.

- index.d.ts
#194 never updated type script file
> Update scroll mouse for 0.4.6

- README.md
> Fix API URL on Readme

- src/mouse.c
> Fixed Linux Y-axis scrolling bug

- package-lock.json
- package.json
- src/mouse.c
- src/robotjs.cc
- test/all.js
- test/bitmap.js
- test/integration/keyboard.js
- test/integration/mouse.js
- test/integration/screen.js
- test/keyboard.js
- test/mouse.js
- test/screen.js
This PR adds integration tests that allow us to be confident in the changes we're making. Utilizing [Target Practice](https://github.com/octalmage/targetpractice), we are now able to confirm that the mouse was clicked instead of just that mouse click was called. I wrote a couple of tests like clicking the mouse, typing, scrolling and reading a pixel color, but really we should rewrite all tests using Target Practice. 
This PR also replaces Tape with Jasmine. Having access to beforeEach and afterEach greatly simplified the actual tests. 
Resolves #154.
> Add integration tests.

- .travis.yml
- package-lock.json
- package.json
> Deploy scripts.

- package-lock.json
- src/robotjs.cc
> v8::{Handle => Local} for node 12 compatibility

- .travis.yml
- appveyor.yml
The tests still have some failure on LINUX + NodeJS >= 12 which will be fix with another PR
> Update the builder configs

- src/keypress.c
Addresses issue #566 created by pr #527 
All the code added is X11 exclusive... this PR should not interfere with Windows or MacOS
> Fix X11 support stripped with windows PR
