- src/robotjs.cc
This PR makes a few enhancements to keyboard functionality.
- Exposes the KeyToggle function for use in Robotjs.
- Adds modifiers for KeyTap and KeyToggle.
- Adds the ability to write single characters to KeyTap and KeyToggle.
- Adds keys that were missing from KeyTap to both KeyTap and KeyToggle.
- Fixes a bug I noticed in KeyTap. Seems it was not releasing the key. I used the OSX keyboard viewer to see this. As already suggested in one of the issues, I added a sleep function to fix. I did not fix this in the mouse events, but the mssleep function can be reused.
Closes #7 
Closes #14
> Enhancements to Keyboard Functions

- binding.gyp
- src/MMBitmap.h
- src/deadbeef_rand.h
- src/io.h
- src/rgb.h
- src/robotjs.cc
- src/screengrab.c
- src/snprintf.c
- src/snprintf.h
- src/str_io.h
- src/uthash.h
- test/all.js
Thanks to the work of many, we now have full Windows support! 
Closes #2.
> Full Windows Support!

- src/robotjs.cc
This should fix the issue of negative values being returned when calling
getMousePos on extended displays
> Fix for #15

- .travis.yml
nan has been updated to v2.0.0 to include support for io.js v3, but it requires significant code changes. This change allows io.js v3 builds to fail until I can update nan.
#71 related.
> io.js v3.0.0 is not supported, so it's allowed to fail. 

- src/robotjs.cc
This is done to improve the reliability of scripts because a window sometimes can't keep up with a rapid flood of mouse/key events.
#14.
> Make global delays configurable. 

- src/robotjs.cc
Instead of 0 or 1 for the second argument, allow “up” or “down”. This is more user friendly and matches mouseToggle.
This change breaks backwards compatibility, but before 1.0.0 this is alright. 
Closes #101.
> Allow up or down for keyToggle.

- src/keypress.c
The fix is for Windows only, other platforms should be unaffected.
The return value for toggleKeyCode (which uses VkKeyScan) contains the encoded modifiers (eg SHIFT in my case). 
The modifiers are now extracted into the format expected by Robotjs.
This fixes issue #108
> Fixed an issue with 'typeString' under Windows. 

- src/keypress.c
This fixes a warning introduced in d99f3bb8264f6925ac0da2356c55f33f84388e79. 
```
> robotjs@0.3.4 install /private/var/tmp/robot/node_modules/robotjs
> node-gyp rebuild
CXX(target) Release/obj.target/robotjs/src/robotjs.o
CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
CC(target) Release/obj.target/robotjs/src/mouse.o
CC(target) Release/obj.target/robotjs/src/keypress.o
../src/keypress.c:73:6: warning: unused variable 'modifiers' [-Wunused-variable]
int modifiers;
^
1 warning generated.
CC(target) Release/obj.target/robotjs/src/keycode.o
CC(target) Release/obj.target/robotjs/src/screen.o
CC(target) Release/obj.target/robotjs/src/screengrab.o
CC(target) Release/obj.target/robotjs/src/snprintf.o
CC(target) Release/obj.target/robotjs/src/MMBitmap.o
SOLINK_MODULE(target) …
```
> Prevent unused variable warning for Mac and Linux.

- src/mouse.c
- src/mouse.h
- src/robotjs.cc
This adds a new dragMouse function that allows you to do things like:
```
robot.moveMouse(300, 300);
robot.mouseToggle('down');
robot.dragMouse(400, 300);
robot.mouseToggle('up');
```
It just calls moveMouse for platforms other than OS X.
Resolves #127.
> Added dragMouse function

- src/robotjs.cc
This pull allows you to call keyTap and keyToggle with an array of string flags (as well as a single string, for backwards compatibility). For example, you can do:
```js
robot.keyTap('g', ['command', 'shift']);
robot.keyToggle('g', 'down', ['command', 'shift']);
robot.keyToggle('g', 'up', ['command', 'shift']);
```
> Added support for arrays of key flags

- src/MMBitmap.c
- src/MMBitmap.h
- src/robotjs.cc
This should fix the Screen Capture bug. 
Unfortunately I seem to have messed up the branch a bit so I cannot merge. (Need to learn Git properly)
The changes in the ```Screen Caputre Fix``` should fix it.
The problem was the memory was being de-allocated even though the ownership of the memory was transferred to the Buffer object. By adding the callback, which will be called when the object is Garbage collected, there wont be any memory leaks.
> Screen capture fix

- src/robotjs.cc
Example usage: 
```
var robot = require("robotjs");
robot.typeStringDelayed("Hello World", 120);
```
First parameter is the string to type, second is characters per minute (cpm).
> Added typeStringDelayed.

- src/keypress.c
- src/keypress.h
I'm using RobotJS to simulate keyboard input into an RDP session. However, because the Windows RDP client listens for scan codes instead of the key codes (for security reasons?), simulating key events with RobotJS doesn't work. See [this thread on SO](https://stackoverflow.com/questions/345147/how-to-simulate-keybard-input-to-a-remote-desktop-session#345302).
This PR adds the correct scancode using [MapVirtualKey](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646306(v=vs.85).aspx). With this change, RobotJS can send key events locally and through an RDP session. Tested on Windows Server 2012 and Windows 10.
Cheers,
Mike
> Map virtual key before triggering keybd_event

- src/mouse.c
Fix mouse scroll on Windows XP, see [#97](https://github.com/octalmage/robotjs/issues/97).
C89 (2008 redistributables (XP)) requires variable declarations to be on top of a block. Newer versions have better support for C99, which is more flexible in this.
Tested with 2008 redistributables on Windows 10.
> fix for #97, mouseScroll Windows XP

- src/keypress.c
I have been working more with RobotJS via RDP, which has been working great so far. 
However, keys with an extended scancode (most notably, media keys) were not sent through correctly with the change from PR #151. To get extended keys to work, the flag `KEYEVENTF_EXTENDEDKEY` needs to be set in `keybd_event` ([docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646304(v=vs.85).aspx)).
I could find no reliable way of querying the OS which keys are extended, so I looked in the src of FreeRDP/FreeRDP ([here](https://github.com/FreeRDP/FreeRDP/blob/master/include/freerdp/scancode.h#L160-L209)), because they have a similar issue.
All the keys that should have an extended scan code are now triggered with the `KEYEVENTF_EXTENDEDKEY` set. So now also media buttons, volume buttons, …
> Extended keys through RDP

- src/robotjs.cc
- src/xdisplay.c
- src/xdisplay.h
I said I would get back to you a few months ago, sorry about that!
The code you mentioned is out of date, so I updated it, it is basically #34 with updates to the nan API
used.
I tested this on my machine and it works as expected.
> add a way to specify the X11 display in Linux

- index.d.ts
according to the documentation the button parameter should be string and not boolean:
mouseToggle([down], [button])
Toggles mouse button.
Arguments
Argument	Description	Default
down	Accepts down or up.	down
button	Accepts left, right, or middle.	left
> Modified the mouseToggle method signature

- README.md
Current behaviour takes you to the old docs which contain a link to the website.
> Link in readme to docs goes straight to website

- src/keypress.c
Here's is preliminary patch for support unicode characters in robotjs for `.typeString()`.
```js
robot.typeString('Àçćéñtéd'); // works
robot.typeString('你好吗？'); // works
robot.typeString('😆💩🌺😍👍😠🐠😝😢🤣😢🦑'); // works
```
This fixes #16 #30
It has does simple UTF-8 parsing (without validation) and I have tested this with Chinese and accented characters [edit: and emjios] on MacOS.
~~However, I have not figured how to have emojis sending yet nor have I have tested it on other platforms although I've tried to make the code changes minimal here.~~
> Support Unicode Characters for .typeString()

- src/mouse.c
- test/mouse.js
It also includes https://github.com/octalmage/robotjs/issues/301.
If accepted, please merge first https://github.com/octalmage/robotjs/pull/306.
Closes #360
> Windows scrolling bug

- src/keycode.c
keyToggle and keyTap are working only with ASCII chars. 
The dictionary with chars and the key codes is generated using the current language and if this chars are not ASCII we won't be able to find the corresponding key code that we need for executing keyToggle. This will result in not printing any chars.
With this patch, no matter of the current language the dictionary will be constructed only from ASCII chars. This fixes the issue.
> keyToggle and keyTap not working on MacOS when the current language is non-Latin

- .gitignore
- package-lock.json
- src/keypress.c
- src/mouse.c
> Fix for #347

- src/keypress.c
It appears that a cast can reduce some of the compile warnings.
See also:
* https://github.com/octalmage/robotjs/issues/183
* https://github.com/octalmage/robotjs/issues/413
The compile warnings were:
```
../src/keypress.c:214:48: warning: incompatible pointer types passing 'unsigned short (*)[2]' to parameter of type
'const UniChar * _Nullable' (aka 'const unsigned short *') [-Wincompatible-pointer-types]
CGEventKeyboardSetUnicodeString(keyEvent, 2, &surrogates);
^~~~~~~~~~~
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:206:59: note: passing argument to parameter 'unicodeString' here
UniCharCount stringLength, const UniChar * __nullable unicodeString)
^
../src/keypress.c:216:48: warning: incompatible pointer types passing 'unsigned long *' to parameter of type …
```
> Reduce compilation warnings

- src/keypress.c
If we do all this work to figure out associated scancodes for virtual keys, we should use them to actually send keystrokes as such.
> Actually send scancodes after figuring them out

- index.d.ts
- src/mouse.c
- src/mouse.h
- src/robotjs.cc
RobotJS fails on Windows 10 environment with multiple displays when a primary display is not located on top left corner of entire virtual screen or displays have different resolutions and dpi scale factors.
It fixes #400
> Fix error with mouse moving in Windows with multiple displays

- src/mouse.c
- src/mouse.h
- src/robotjs.cc
- src/types.h
If the user has more than 1 monitor the coordinates of a monitor can be negative. Before the PR all the parameters for mouseMove and dragMouse were using size_t which is unsigned. That's why it was not possible to pass negative coordinates and move the mouse to a monitor with negative coordinates.
Fix #88
> Multi monitor support for mouseMove and dragMouse

- index.d.ts
- package.json
- src/keypress.c
- src/keypress.h
- src/robotjs.cc
- test/keyboard.js
Tested on Windows and Mac.
* Added a new unicodeTap() method.
* Supported Unicode characters for typeString() as well.
* Aligned the functionality of typeString() and typeStringDelayed() methods.
* Unit tests are added.
Additional comments can be found on the separate commits of this request.
Closes #351, #353, #386, #502
> Unicode tap

- src/keycode.c
At
https://github.com/octalmage/robotjs/blob/b26c7ee0e3dd05420370350e540c48ae9d38f06c/src/keycode.c#L98,
`sizeof(void*)` bytes (probably 8) are written to a memory
segment of 2 bytes (a 16-bit CGKeycode variable), resulting in all
kinds of weird behaviour, like unrelated variables getting NULLed.
Making `code` a a type that can hold `sizeof(void*)` bytes fixes this.
Closes #570
> src/keycode: fix buffer overflow

- package.json
- test/integration/screen.js
The screen test randomly fails if your window manager takes a little bit longer than normal. Which is particularly the case in large screens such as 4k+ monitors or slow GPUs.
I added an optional 1 second delay if the first attempt fails. In Mocha it runs in parallel, so using interval might slow down other tests without any real benefit... hence why I'm using timeout. Speaking of Mocha, it supports retries and is generally better supported than Jasmine... we should switch. The syntax is very similar.
> Harden screen test
